# Generated by Django 2.0.7 on 2018-12-11 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='idLista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Lista'),
            preserve_default=False,
        ),
    ]
