# Generated by Django 2.0.7 on 2018-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181210_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='correo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
