# Generated by Django 2.0.7 on 2018-12-13 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181212_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Ciudad'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Region'),
        ),
    ]
