# Generated by Django 2.1.2 on 2018-12-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181212_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoCompra',
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
