# Generated by Django 2.1.2 on 2018-12-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181212_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='notas',
            field=models.CharField(default='', max_length=500),
        ),
    ]
